version: '3.7'

volumes:
  vol_mysql:

services:
  mysql:
    image: bitnami/mysql:8.0
    env_file:
      - .env
    volumes:
      - vol_mysql:/bitnami/mysql/data
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}

  api:
    image: bitnami/node:14.15.0
    env_file:
      - .env
    command: ./wait-for-it.sh --host=mysql --port=3306 --timeout=25 -- npm run dev:server
    ports:
      - ${PORT}:${PORT}
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    depends_on:
      - mysql
